### ISSUE TITLE
R disabled by accident or temporarily?

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#158]
I just initialized a new arbor instance 8/20/2015 and found out just now that R computation is gone.   I reprovisioned on 8/22 in case but same result.  Running an R script results in "invalid mode: r" error message. 

Did I catch the master branch of tangelohub out of sync with the new romanesco architecture?  I'll try switching to the romanesco plug-in branch on romanesco and tangelohub.

**Comment by zachmullen** [comment]
Hi @curtislisle , this is due to a recent change in romanesco in which we created a plugin architecture within romanesco. R capabilities were moved within a plugin, so a little extra configuration needs to be done to get it enabled. I will update that in the ansible playbook this weekend.

**Comment by curtislisle** [comment]
@zachmullen, thanks so much for your quick answer and willingness to work on the playbook.  I will wait for the update, then plan to pull the update and reprovision my instance.  Glad I wasn't just going crazy :-)

**Comment by zachmullen** [comment]
Just realized I actually opened a PR to fix this issue at the same time I created the romanesco change:  #157 . It hasn't been officially QA'd yet, though. @curtislisle could you checkout that branch and rebuild the vagrant box and see if it fixes the problem?

**Comment by curtislisle** [comment]
I noticed the corresponding changes.  So I just check out the PR for tangelohub and the corresponding romanesco commit, right?  Will be glad to.

**Comment by zachmullen** [comment]
Yep, that's correct. If that works, I will go ahead and merge #157.

**Comment by curtislisle** [comment]
I checked out the "support-romanesco-plugin-framework branch', performed an "npm instdall" in  /vagrant to rebuild the app, and then went to /vagrant/romanesco and performed a git pull to update romanesco, as well.  TangeloHub comes up but I still receive the "Invalid more: r" command when trying to run an R-based analysis.  Did I miss something?

**Comment by zachmullen** [comment]
It will require re-running `vagrant provision` from your host.

**Comment by curtislisle** [comment]
This worked and R is enabled again! Great!  Thanks for reminding me, reprovisioning failed the first time and I forgot about it by the time I fixed the issue, until your reminder.  So #157 works for me using this branch and the current head of romanesco  ( 8/27 9:03 AM commit c72fef48c3ffa32d5b6f19997519502b79d12f69)!
