### ISSUE TITLE
vagrant provision currently broken

### ISSUE THREAD

**Issue by zackgalbreath** [Kitware/flow#176]
I see the following error when running `vagrant up`:
```
TASK: [romanesco | install girder plugin (also builds web client)] ************ 
...
pkg_resources.DistributionNotFound: The 'six==1.9.0' distribution was not found and is required by girder
```

Looks like requirement mismatch between romanesco & girder.  I think the correct fix here is to update the version of girder available from pip.

**Comment by zackgalbreath** [comment]
To be more clear, romanesco is installing six v1.10.0, while girder seems to want 1.9.0.  [It looks like girder has also moved to 1.10.0](https://github.com/Kitware/girder/blob/master/requirements.txt#L12), hence my recommendation of a version upgrade for pip-installable girder.

**Comment by jeffbaumes** [comment]
I believe @danlamanna has seen this. Is there a fix yet?

**Comment by zachmullen** [comment]
We are due for a new girder release, I'll try and make that happen today.

**Comment by curtislisle** [comment]
Dan has generated a patch that I’ve been using in the meantime.  I do a clone, then patch, then do vagrant up, generally.  Patch attached in the meantime.

**Comment by chinchliff** [comment]
there are similar issues with most of the other dependencies as well (e.g. requests, Mako, others). @curtislisle i didn't see a patch attached... am i just overlooking it? anyway i went into the vm and manually updated /usr/local/lib/python2.7/dist-packages/girder-1.4.1-py2.7.egg-info/requires.txt to match https://github.com/girder/girder/blob/114b5dda576bc0611617a92f88942f3a55dabe7d/requirements.txt, and now the vagrant provisioning seems to be working and i can pull up a running arbor instance on localhost:9080

**Comment by curtislisle** [comment]
@chinchliff , congrats on getting your instance working!  Sorry you had to open the hood and tweak the internal dependencies.  I burned in the previously mentioned patch to the "pin_girder_and_romanesco" branch of this repository, fixing the versions to avoid python six dependency issues.  For now, I use this branch when initializing new instances.  I plan to continue this approach through for the next two months to have stable instance for Arbor use.  In the meantime, Kitware is re-engineering an improved architecture with more type management support. I don't plan to switch our instances over until after the end of April.

**Comment by chinchliff** [comment]
Thanks for the update curt!

**Comment by danlamanna** [comment]
This has been fixed in master.
