### ISSUE TITLE
Client error after provision, then goes away

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#178]
I believe this started happening in January 2016.  

The very first time a new vagrant instance is provisioned, the first analysis run attempt from the GUI fails.  This goes away after a browser refresh  or two (or maybe something else I did).  It has also happened to Luke on the Amazon public Arbor today.  Notice the undefined itemId in the call below. 

HTTP fetch failed (http://54.145.243.145:9080/girder/api/v1/item/undefined/download). Response: {"field": "id", "message": "Invalid ObjectId: undefined", "type": "validation"}<class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request  File "/vagrant/romanesco/romanesco/__main__.py", line 26, in run    retval = romanesco.run(*pargs, **kwargs)  File "/vagrant/romanesco/romanesco/utils.py", line 285, in wrapped    return fn(*args, **kwargs)  .....

**Comment by danlamanna** [comment]
Can you reliably reproduce this?

I can't, but I have a hunch the item isn't being saved to the collection before the analysis is run. I'm not sure if Flow traditionally supports that or not.

**Comment by curtislisle** [comment]
Yes, that's the issue.  It is reproducible.  It happens when a dataset is just drag/dropped onto the UI button and an analysis is run on the dataset in local storage (not from a collection).  To reproduce:

go to arbor1.arborworkflows.com
select the "Data' collection
select "geospiza_characters.csv" and download to the local system
drag & drop geospiza_characters.csv, so we have a local copy in the browser
Enable the Base collection and select analysis "Aggregate Table by average"
- select the browser-resident table file just uploaded; aggregate on any variable
- Client Error: Bad Request results.  

The analyses work when the datasets are from a collection or were created by a previous Romanesco job, even if they are only browser resident.  Analyses only fail on data "just dropped on the UI", as far as my experiments.

**Comment by jeffbaumes** [comment]
@curtislisle could you try #180 and see if it works for you?

**Comment by curtislisle** [comment]
Thanks for looking at this.  I will try it tonight.  I have to step out for a few hours now.  If I get a chance before I go, I’ll try it.

**Comment by curtislisle** [comment]
This fixes the problem.  browser local tables work again.  I made the code change from the commit directly on the Amazon AWS instance and followed with npm install.  Arbor/AWS works again. Thanks!
