### ISSUE TITLE
easy mode apps just stopped working

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#183]
Sadly, the easy mode on the new Amazon instances and Josef's new local instance from a vagrant up just stopped working a few days ago.  The error seems consistent across instances: as soon as I access the easy mode app, an error pops up on main.js, the datasetsView seems to have become undefined, so users can't drop onto the dataset button.  If anyone is able to look into  this.  I'd appreciate it.  Thanks. 

 // override upload function for simple mode
 app.datasetsView.upload = function (file) {     <-- error here (line 45)
        var reader = new FileReader();

error: 
Uncaught TypeError: Cannot set property 'upload' of undefined

**Comment by jeffbaumes** [comment]
Sorry for being slow to respond. @danlamanna looked into this a bit earlier but didn't get too far. Is there a URL where this is hosted that is showing the error - maybe we can track it down from there. It seems the app is failing before it can get to this line to construct the `datasetsView`:

https://github.com/Kitware/flow/blob/a5f2f24594ac69e5faa879740eb21d2f6e3d3d8b/app/src/views/DatasetManagementView.js#L168

**Comment by curtislisle** [comment]
Thanks for getting  back. I was  busy with arbor viz apps and don't know backbone, so figured it is better to have others look at this.  I had the problem on both Amazon instances: 

arbor1.arborworkflows.com
arbor2.arborworkflows.com

**Comment by curtislisle** [comment]
The fix has been checked in on master and on pinned_romanesco_and girder branch.  Closing issue.
