### ISSUE TITLE
vagrant up failure

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/flow#194]
This is likely due to my deep ignorance of flow's architecture, but `vagrant up` gives me this error:

`fatal: [flow]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "dpkg_options": "force-confdef,force-confold", "force": false, "name": "rabbitmq-server", "only_upgrade": false, "package": ["rabbitmq-server"], "purge": false, `**"state": "absent\n"**`, "update_cache": true}, "module_name": "apt"}, "msg": `**"value of state must be one of: installed,latest,removed,absent,present,build-dep, got: absent\n"**`}`

I'm guessing there's a stray newline in some configuration file somewhere?

**Comment by danlamanna** [comment]
[This thread](https://github.com/Kitware/flow/pull/173#issuecomment-188785657) should give some background, but the tldr is to downgrade Ansible to < 2.0 for now.

**Comment by alex-r-bigelow** [comment]
For the record, here are the snags I hit in the installation process + their fixes:
```
virtualenv env
source env/bin/activate
pip install ansible==1.9.4

https://github.com/Kitware/flow.git
cd flow
vagrant up
```
Another error pops up that has something to do with libffi. To fix it:
```
vagrant ssh
/opt/.girderenv/bin/pip install -r /opt/girder_worker/requirements.txt
exit
vagrant provision
```
Now a different error pops up when it tries to create the Girder user:
```
request() got an unexpected keyword argument 'json'
```
At this point, I can go to localhost:8080, and set up everything manually:
- Register a *girder* user (password: *girder*)
- Set up the assetstore by typing:
```
  vagrant ssh
  sudo mkdir /opt/data
  sudo chgrp girder /opt/data
  sudo chown girder /opt/data
```
- Go to Admin Console -> Assetstores -> Create a new Filesystem assetstore,
  - Assetstore name: Filesystem Assetstore
  - Root directory: /opt/data
- Then go to Admin Console -> Plugins
  - Enable flow
  - Enable girder-worker
  - Restart Server

I think at this point it's technically working...? Are there example datasets / etc that I should be uploading?

**Comment by alex-r-bigelow** [comment]
As these workarounds can get it up and running, I'm going to close this for now.

**Comment by curtislisle** [comment]
Can we have a branch of Flow that builds reliably coming week during the Evolution meeting, when Arbor is getting exposure to the Phylogenetics community during the booth exhibit on June 14-17?   

If girder has changed and is incompatible with Flow temporarily, lets create a branch that runs to completion, even if it means pinning the version of girder down again.  This is a week where new people will do 'vagrant up' and I want it work without having to go through the hand stuff Alex had to do.  

FYI. I just tried ‘vagrant up’ on both the master branch and on origin/add-libssl-requirements-xxx branches and neither continued provisioning all the way through.
