### ISSUE TITLE
Trellis graphics in R don't work with cardoonPlot

### ISSUE THREAD

**Issue by uyedaj** [Kitware/flow#202]
Here are two examples (I get the error on arbor1 and arbor2 instances). In the Trellis analysis, I get the error:
`Operation Failed.
Error in file(con, "rb") : cannot open the connection`

[TrellisFigure.json](http://54.83.6.133:9080/girder#item/577cafd84c46530515578c20)
`{
    "description": "",
    "inputs": [],
    "mode": "r",
    "name": "TrellisFigure",
    "outputs": [
        {
            "format": "png.base64",
            "id": "plot",
            "name": "plot",
            "type": "image"
        }
    ],
    "script": "library(cardoonTools)\nlibrary(lattice) \nattach(mtcars)\n\n# create factors with value labels \ngear.f<-factor(gear,levels=c(3,4,5),\n  \tlabels=c(\"3gears\",\"4gears\",\"5gears\")) \ncyl.f <-factor(cyl,levels=c(4,6,8),\n   labels=c(\"4cyl\",\"6cyl\",\"8cyl\")) \n\n# kernel density plot \nplotfn <-  function() densityplot(~mpg, \n  \tmain=\"Density Plot\", \n  \txlab=\"Miles per Gallon\")\n  \t\n\nplot <- cardoonPlot(expression(plotfn()))\nplot <- plot$png"
}`

Compare to BaseGraphics.json
`{
    "description": "",
    "inputs": [],
    "mode": "r",
    "name": "BaseFigure",
    "outputs": [
        {
            "format": "png.base64",
            "id": "plot",
            "name": "plot",
            "type": "image"
        }
    ],
    "script": "library(cardoonTools)\nlibrary(lattice) \nattach(mtcars)\n\n# create factors with value labels \ngear.f<-factor(gear,levels=c(3,4,5),\n  \tlabels=c(\"3gears\",\"4gears\",\"5gears\")) \ncyl.f <-factor(cyl,levels=c(4,6,8),\n   labels=c(\"4cyl\",\"6cyl\",\"8cyl\")) \n\n# kernel density plot \nplotfn <-  function() plot(rnorm(100))\n  \t\n\nplot <- cardoonPlot(expression(plotfn()))\nplot <- plot$png"
}`

**Comment by uyedaj** [comment]
Same thing happens on newest arbor.arborworkflows.com

**Comment by danlamanna** [comment]
I'm not familiar with R, but is it possible something is wrong with the script itself?

The error (which seems to be spawned by `cardoonPlot`) is that a png file under /tmp doesn't exist. I ran the script under strace and it looks like the only time it tries to access that file is to read it - so that analysis isn't creating the image anywhere.

pinging @jeffbaumes if he has any ideas.

**Comment by curtislisle** [comment]
thanks for looking into this, Dan.  CardoonPlot has malfunctioned before, but I have never looked inside to determine why/when.  

Unfortunately, the scatterplot function in arbor seems to not be working for the CSVs I tried yet, either, or I would have suggested this alternative.

**Comment by curtislisle** [comment]
Josef,
I will look at this tomorrow morning if it is still broken.

**Comment by jeffbaumes** [comment]
I vaguely remembered @hafen (original cardoonTools author) mentioning that sometimes `expression()` is not needed. And indeed if you remove the `expression()` wrapping from the trellis example it seems to work. Unfortunately I cannot recall the details of when it is needed and when it is not.

**Comment by uyedaj** [comment]
You're correct @jeffbaumes, in the toy example I gave above, removing expression() does indeed fix it. However, this does not solve the problem in my real example (sorry for not testing the toy example enough...). In fact, I don't need to use cardoonTools to recreate the problem at all, and the result is different whether I run the script interactively in R or when I run it through Arbor. In fact, I can run this exact script in R via SSH on arbor1 without any issue, but it fails when run via Arbor (same error message as above):
`{
    "description": "",
    "inputs": [],
    "mode": "r",
    "name": "TrellisFigure",
    "outputs": [
        {
            "format": "png.base64",
            "id": "GLSplot",
            "name": "GLSplot",
            "type": "image"
        }
    ],
    "script": "y <- rnorm(100)\nx <- rnorm(100)\n\nglsfit <- nlme::gls(y~x)\n\nfile <- tempfile(fileext = sprintf(\".%s\", \"png\"))\nresult <- list()\npng(file, width=1000, height=1000, res=72)\nplot(glsfit)\ndev.off()\nbytes <- file.info(file)$size\nresult$png <- base64enc:::base64encode(readBin(file, \"raw\", n = bytes))\nfile.remove(file)\n\nGLSplot <- result$png"
}`

**Comment by uyedaj** [comment]
The issue is sourcing the script does not tell R to make the plot for Trellis graphics. Not an Arbor problem: http://stackoverflow.com/questions/6783120/r-package-lattice-wont-plot-if-run-using-source
Thanks guys.

**Comment by jeffbaumes** [comment]
Wow that is a crazy one. Thanks for digging into it.

**Comment by hafen** [comment]
The `cardoonPlot()` function is looking for either an expression (when using base R graphics) or a lattice or ggplot2 object.  It doesn't know what to do with a function (I suppose it should check for that).

So the first json shown should be changed to something like this:

```
{ "description": "", "inputs": [], "mode": "r", "name": "TrellisFigure", "outputs": [ { "format": "png.base64", "id": "plot", "name": "plot", "type": "image" } ], "script": "library(cardoonTools)\nlibrary(lattice) \nattach(mtcars)\n\n# create factors with value labels \ngear.f<-factor(gear,levels=c(3,4,5),\n \tlabels=c(\"3gears\",\"4gears\",\"5gears\")) \ncyl.f <-factor(cyl,levels=c(4,6,8),\n labels=c(\"4cyl\",\"6cyl\",\"8cyl\")) \n\n# kernel density plot \nplotObj <- densityplot(~mpg, \n \tmain=\"Density Plot\", \n \txlab=\"Miles per Gallon\")\n \t\n\nplot <- cardoonPlot(expression(plotObj))\nplot <- plot$png" }
```
