### ISSUE TITLE
girder version change cause instability?

### ISSUE THREAD

**Issue by curtislisle** [Kitware/flow#209]
I was not able to build the origin/master, or recent switch-to-ansible-galaxy or release 0.0.1 versions of Flow today.  Each failed provisioning in girder-related places.  Below is the error received 'vagrant up' on origin/master:

(p.s. I noticed the NodeJS versions on the trusty64 core used for a base are pretty old)
vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ nodejs -v
v0.10.37
vagrant@vagrant-ubuntu-trusty-64:~$ npm -v
1.4.28

Here is excerpted errors from the failure during vagrant provisioning:

TASK: [girder-install | Install frontend assets] ****************************** 
...
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})

/opt/girder/node_modules/grunt-shell/tasks/shell.js:2
const exec = require('child_process').exec;
^^^^^

npm ERR! girder@1.5.2 postinstall: `grunt init && grunt`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the girder@1.5.2 postinstall script.

....

Traceback (most recent call last):
  File "/opt/.girderenv/bin/girder-install", line 11, in <module>
    load_entry_point('girder', 'console_scripts', 'girder-install')()
  File "/opt/girder/girder/utility/install.py", line 211, in main
    parsed.func(parsed)
  File "/opt/girder/girder/utility/install.py", line 86, in install_web
    runNpmInstall(dev=opts.development, npm=opts.npm)
  File "/opt/girder/girder/utility/install.py", line 75, in runNpmInstall
    proc.returncode)

**Comment by danlamanna** [comment]
Yeah @curtislisle you're spot on, I'm pretty sure it's an issue with node/npm being too old. This stopped working recently and since #207 is in progress it didn't make sense to fix it.

This should be solved in #207 already - I'm going to make sure that PR is stable tomorrow since I noticed you had an issue with it.

**Comment by curtislisle** [comment]
this is resolved.  the build works fine.
